### ISSUE TITLE
ReferenceError: Can't find variable: Zone

### ISSUE THREAD

**Issue by begbeder** [Raphcal/cordova-plugin-cors#1]
Hi!
I am using a plugin and getting an error in ios Safari.
I do not use zone.js

this.zone = Zone ? Zone.current : undefined; // ReferenceError: Can't find variable: Zone

**Comment by Raphcal** [comment]
Hello,
Sorry for that. I am going to fix this as soon as possible.

**Comment by begbeder** [comment]
Thanks for your work.

**Comment by Raphcal** [comment]
Fixed in version 1.0.4 :)
