### ISSUE TITLE
No implementation for  XMLHttpRequest.overrideMimeType(mimeType)

### ISSUE THREAD

**Issue by avienne** [Raphcal/cordova-plugin-cors#15]
Found this plugin very usefull but my application is dependent on a third party library that uses the 
XMLHttpRequest.overrideMimeType(mimeType)

this plugin does not implement this function.

**Comment by Raphcal** [comment]
Do you know which mimeType is expected by the third party library ? I can simply store the given MIME type and change the Content-Type value accordingly but since I don't parse XML response it may be of no use to you if the library expects an XML document.

**Comment by avienne** [comment]
For the moment I they use this function to load arbitrary text files as text/html. 
It can also be application/json some times. 
My guess is that they want to load text files (json and custom texts) and use the same callback every time.

**Comment by Raphcal** [comment]
I published a version 1.3.0 that may fix your use case. Can you give it a try ?

**Comment by avienne** [comment]
Gave it a try today. Even if the overrideMimeType worked I still have issue and I do not know if it is cors plugins issue or another problem.

Got the 
<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />

in the config.xml of the procjet (using cordova-ios 6.1.0)

this is the third party code calling the function : 

 let request = new XMLHttpRequest();
        request.overrideMimeType("text/html");
        request.open("GET", url, true);
        let done = () => {
            this.finish(url, request.status, request.responseText);
        };
        request.onload = done;
        request.onerror = done;
        request.send();


Got a request.status 200 but nothing in the request.responseText object.

I do not see the request throught the safari web inspector nor in a web proxy I set to catch native http calls made from the native part of the app

In Xcode I do have this : 
NSErrorFailingURLKey=app://localhost/assets/rest_of_the_path_to_asset,
 _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <4C8D7370-7A96-487E-A718-85827DFB6EEF>.<86>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <4C8D7370-7A96-487E-A718-85827DFB6EEF>.<86>, NSUnderlyingError=0x282a38540 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}}

could this be related to the app://localhost/ part ?

**Comment by Raphcal** [comment]
`app://` is a custom URL scheme registered on the web view instance. I think I've seen this URL scheme in old version of the Ionic Framework to deal with CORS requests. Sadly, this plugin cannot talk with the web view in a way to make this call work 😞
