### ISSUE TITLE
App crashing when try to make HTTP calls from Axios 

### ISSUE THREAD

**Issue by grandhisubrahmanyam35** [Raphcal/cordova-plugin-cors#6]
In my cordova application using axios javascript library to make Http/Https calls.  When I make API calls from *XMLHttpRequest* working properly. The problem is only with Axios.

Can you help on this?

[Axios Library](https://www.npmjs.com/package/axios) for reference.

**Comment by Raphcal** [comment]
Do you have an error message that could help identify the problem (in the browser or in Xcode console) ?

**Comment by grandhisubrahmanyam35** [comment]
@Raphcal I don't see any error. After I debug I got to know that When I add **new Date().getTimezoneOffset()** value to the header App is crashing. Not sure why. Can you help me with this?

**Comment by Raphcal** [comment]
I think it is because getTimezoneOffset returns a number. I will add support for number values but in the meantime you should be able to use :
~~~
'' + new Date().getTimezoneOffset()
~~~

**Comment by grandhisubrahmanyam35** [comment]
@Raphcal What you said is true.  The same thing is happening when the header datatype value is **Boolean**. Could you please handle datatypes? I was stuck on this for a few days.

**Comment by Raphcal** [comment]
Sorry for that, I will try to add support for this tomorrow.

**Comment by grandhisubrahmanyam35** [comment]
@Raphcal Thanks for your quick reply. Meanwhile, I will fork your repo. If you don't mind can you guide me where I have to change I will try to make those changes? Basically, I am a JS developer I don't have the time it's very emergency in my case. 

It would be great if you can help on this ASAP

**Comment by Raphcal** [comment]
I released a version 1.1.3, it should fix the problem with number type headers. I haven't tested it thoroughly though, let me known if it works for you.

**Comment by grandhisubrahmanyam35** [comment]
Thanks @Raphcal  I added support for Boolean datatype as well. I don't have permission to raise PR otherwise would have raised PR.

Also Could you please let me know after new release.

**Comment by Raphcal** [comment]
Version 1.1.3 should already support boolean values.

**Comment by grandhisubrahmanyam35** [comment]
Yes, it's working @Raphcal . Thanks for your quick help. You saved me. Happy to close this issue.

**Comment by grandhisubrahmanyam35** [comment]
@Raphcal I have raised another issue https://github.com/Raphcal/cordova-plugin-cors/issues/9. Could you please check
