### ISSUE TITLE
App crashing when HTTP call has **accept=application/pdf**  

### ISSUE THREAD

**Issue by grandhisubrahmanyam35** [Raphcal/cordova-plugin-cors#9]
I am using this Cordova plugin in my Cordova application. This plugin saved me a lot of my time. It worked for all my cases except the 1 following case.

Whem I am making API with **https://vsltst1.applaudsolutions.com/OA_HTML/applaud/api/assignments/259/oracle-payslips/US/8809896?_accept=application/pdf&inline=true&biPublisherTemplate=#** app got broken. After I debug got to know it's because of **accept** query parameter. 

If I change from **application/pdf** to **application/json** it's working. seems like Mime-types not handled properly. @Raphcal Could you please help with this?

**Comment by Raphcal** [comment]
Yes binary content is not yet supported by the plugin. Do you intend to use `responseType` to change the expected type of `response` and to use it instead of `responseText` to access the binary data as an Uint8Array ?

**Comment by Srinivas-Alle** [comment]
Hi @Raphcal. Really helpful for me if you close this issue. Blocked by this.

**Comment by grandhisubrahmanyam35** [comment]
@Raphcal Yes, I am expecting the response-type to different compared with the existing one. 

Now getting response-type as **application/json**
Expecting response-type as **application/pdf**

**Comment by grandhisubrahmanyam35** [comment]
@Raphcal I see you have already created a branch and made a commit init. When I can expect the new release with new changes?

**Comment by Srinivas-Alle** [comment]
Hi @Raphcal any update on this?

**Comment by Raphcal** [comment]
Sorry for the delay, I just released a fix for this in version 1.2.0.
